import { VideoItem, ChunkResult } from '../types';

export const INITIAL_VIDEOS: VideoItem[] = [
  {
    id: 'vid-1',
    youtube_id: 'jNQXAC9IVRw',
    title: 'Overcoming Imposter Syndrome as a Content Creator (My Personal System)',
    channel: 'Creator Craft',
    duration_formatted: '18:45',
    total_seconds: 1125,
    thumbnail_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80',
    chunk_count: 24,
    uploaded_at: '2026-06-12',
    category: 'Mindset & Psychology'
  },
  {
    id: 'vid-2',
    youtube_id: 'L_LUpnjgPso',
    title: 'How I Recovered from Severe Creator Burnout & Rebuilt My Workflow',
    channel: 'Creator Craft',
    duration_formatted: '24:10',
    total_seconds: 1450,
    thumbnail_url: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&auto=format&fit=crop&q=80',
    chunk_count: 32,
    uploaded_at: '2026-05-20',
    category: 'Mindset & Psychology'
  },
  {
    id: 'vid-3',
    youtube_id: '9YfHM8jJ54Y',
    title: 'Monetizing a Solo Podcast: Brand Deals vs Digital Products vs Subscriptions',
    channel: 'Creator Craft',
    duration_formatted: '32:15',
    total_seconds: 1935,
    thumbnail_url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=600&auto=format&fit=crop&q=80',
    chunk_count: 42,
    uploaded_at: '2026-04-15',
    category: 'Monetization'
  },
  {
    id: 'vid-4',
    youtube_id: 'v7AYKMP6rOE',
    title: 'Mastering YouTube Storytelling: Retention Hooks & Emotional Pacing',
    channel: 'Creator Craft',
    duration_formatted: '21:05',
    total_seconds: 1265,
    thumbnail_url: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=600&auto=format&fit=crop&q=80',
    chunk_count: 28,
    uploaded_at: '2026-07-01',
    category: 'Production'
  },
  {
    id: 'vid-5',
    youtube_id: 'f9V024c0C78',
    title: 'My Complete 2026 Studio Lighting & Audio Setup for Solo Video Essays',
    channel: 'Creator Craft',
    duration_formatted: '15:30',
    total_seconds: 930,
    thumbnail_url: 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=600&auto=format&fit=crop&q=80',
    chunk_count: 20,
    uploaded_at: '2026-07-18',
    category: 'Equipment & Gear'
  },
  {
    id: 'vid-6',
    youtube_id: '3JZ_D3ELwOQ',
    title: 'Why Most Creators Fail at Newsletter Growth (And How to Fix It)',
    channel: 'Creator Craft',
    duration_formatted: '19:40',
    total_seconds: 1180,
    thumbnail_url: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=600&auto=format&fit=crop&q=80',
    chunk_count: 26,
    uploaded_at: '2026-03-30',
    category: 'Audience Growth'
  }
];

export const INITIAL_CHUNKS: ChunkResult[] = [
  {
    id: 'c-101',
    video_id: 'vid-1',
    video_title: 'Overcoming Imposter Syndrome as a Content Creator (My Personal System)',
    channel: 'Creator Craft',
    youtube_id: 'jNQXAC9IVRw',
    start_sec: 142,
    end_sec: 187,
    start_timestamp: '02:22',
    end_timestamp: '03:07',
    text: "Whenever I get hit with severe imposter syndrome before filming, I look at my evidence log. The secret is that imposter syndrome isn't a lack of talent—it's a memory loss problem. You literally forget every single piece of value you've ever delivered to your audience. Keeping a dedicated folder of positive emails and comments breaks that cognitive trap instantly.",
    score: 0.94,
    matched_concepts: ['imposter syndrome', 'memory loss problem', 'evidence log'],
    thumbnail_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'c-102',
    video_id: 'vid-1',
    video_title: 'Overcoming Imposter Syndrome as a Content Creator (My Personal System)',
    channel: 'Creator Craft',
    youtube_id: 'jNQXAC9IVRw',
    start_sec: 485,
    end_sec: 530,
    start_timestamp: '08:05',
    end_timestamp: '08:50',
    text: "People ask how to feel qualified to speak on a topic. My rule: talk about your experience, not universal truth. You don't need a PhD to share what worked for you last week. Being one step ahead of someone in your journey makes you more relatable than an untouchable expert sitting in an ivory tower.",
    score: 0.88,
    matched_concepts: ['qualified to speak', 'experience', 'relatable'],
    thumbnail_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'c-201',
    video_id: 'vid-2',
    video_title: 'How I Recovered from Severe Creator Burnout & Rebuilt My Workflow',
    channel: 'Creator Craft',
    youtube_id: 'L_LUpnjgPso',
    start_sec: 310,
    end_sec: 355,
    start_timestamp: '05:10',
    end_timestamp: '05:55',
    text: "Burnout hit me hardest when I separated my creative identity from rest. I was posting 3 videos a week on a relentless treadmill. The breakthrough came when I switched to batch-scripting and batch-recording. By batching research on Mondays and recording on Tuesdays, I freed up 4 days of uninterrupted deep work or rest.",
    score: 0.92,
    matched_concepts: ['burnout', 'batch-recording', 'relentless treadmill'],
    thumbnail_url: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'c-202',
    video_id: 'vid-2',
    video_title: 'How I Recovered from Severe Creator Burnout & Rebuilt My Workflow',
    channel: 'Creator Craft',
    youtube_id: 'L_LUpnjgPso',
    start_sec: 720,
    end_sec: 765,
    start_timestamp: '12:00',
    end_timestamp: '12:45',
    text: "When you feel exhausted by content creation, it's rarely the filming itself—it's the friction of decided what to do next. Having a pre-validated backlog of 20 content concepts completely eliminates the mental paralysis of starting from a blank page every single morning.",
    score: 0.85,
    matched_concepts: ['exhausted', 'friction', 'pre-validated backlog'],
    thumbnail_url: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'c-301',
    video_id: 'vid-3',
    video_title: 'Monetizing a Solo Podcast: Brand Deals vs Digital Products vs Subscriptions',
    channel: 'Creator Craft',
    youtube_id: '9YfHM8jJ54Y',
    start_sec: 540,
    end_sec: 585,
    start_timestamp: '09:00',
    end_timestamp: '09:45',
    text: "Sponsorship deals pay the bills short-term, but owned digital assets build actual long-term equity. A creator with 5,000 hyper-engaged podcast listeners selling a $150 cohort or digital tool can out-earn a channel with 100,000 passive subscribers relying solely on AdSense revenue.",
    score: 0.91,
    matched_concepts: ['brand deals', 'digital products', 'monetizing'],
    thumbnail_url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'c-302',
    video_id: 'vid-3',
    video_title: 'Monetizing a Solo Podcast: Brand Deals vs Digital Products vs Subscriptions',
    channel: 'Creator Craft',
    youtube_id: '9YfHM8jJ54Y',
    start_sec: 1120,
    end_sec: 1165,
    start_timestamp: '18:40',
    end_timestamp: '19:25',
    text: "Negotiating CPM pricing for podcast ads: never quote flat rate per download upfront. Always bundle podcast host-read spots with your email newsletter integration and social clips. Packaging cross-platform sponsorships commands 3x higher deal values.",
    score: 0.86,
    matched_concepts: ['pricing', 'sponsorships', 'negotiating CPM'],
    thumbnail_url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'c-401',
    video_id: 'vid-4',
    video_title: 'Mastering YouTube Storytelling: Retention Hooks & Emotional Pacing',
    channel: 'Creator Craft',
    youtube_id: 'v7AYKMP6rOE',
    start_sec: 95,
    end_sec: 140,
    start_timestamp: '01:35',
    end_timestamp: '02:20',
    text: "The first 30 seconds of your video determine 80% of your audience retention. Don't waste time saying 'Hey guys welcome back to the channel'. Jump directly into the tension or core problem. Show, don't just explain, why the next 10 minutes matter to their life.",
    score: 0.93,
    matched_concepts: ['retention hooks', 'storytelling', 'first 30 seconds'],
    thumbnail_url: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'c-501',
    video_id: 'vid-5',
    video_title: 'My Complete 2026 Studio Lighting & Audio Setup for Solo Video Essays',
    channel: 'Creator Craft',
    youtube_id: 'f9V024c0C78',
    start_sec: 215,
    end_sec: 260,
    start_timestamp: '03:35',
    end_timestamp: '04:20',
    text: "Good audio beats crisp 4K video every single time. Viewers will tolerate mediocre 1080p camera quality, but echoing, harsh audio makes people click away in seconds. Investing $150 in a dynamic broadcast mic and basic acoustic treatment is the highest ROI studio upgrade you can make.",
    score: 0.89,
    matched_concepts: ['audio setup', 'studio lighting', 'mic acoustic treatment'],
    thumbnail_url: 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'c-601',
    video_id: 'vid-6',
    video_title: 'Why Most Creators Fail at Newsletter Growth (And How to Fix It)',
    channel: 'Creator Craft',
    youtube_id: '3JZ_D3ELwOQ',
    start_sec: 410,
    end_sec: 455,
    start_timestamp: '06:50',
    end_timestamp: '07:35',
    text: "Social media platforms are rented land. Algorithm changes can slash your YouTube reach overnight. Building a direct email newsletter is the only content asset you truly own. Every single video should have a compelling lead magnet directing viewers to join your private email list.",
    score: 0.90,
    matched_concepts: ['newsletter growth', 'rented land', 'email list'],
    thumbnail_url: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=600&auto=format&fit=crop&q=80'
  }
];
